### ISSUE TITLE
Update Bug host For jio operator

### ISSUE THREAD

**Issue by OshekharO** [boychongzen18/Bug-Host-All-Operator#15]
Please update Bug host for this operator:-

https://github.com/boychongzen18/Bug-Host-All-Operator/blob/master/jio.txt

Last updated was 3 years ago.

**Comment by boychongzen18** [comment]
https://github.com/boychongzen18/Bug-Host-All-Operator/blob/master/Update_JIO.txt

**Comment by OshekharO** [comment]
Thankyou very much
